# Generated by Django 2.2.4 on 2019-08-29 19:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(default=None, upload_to='')),
                ('price', models.FloatField(default=None)),
                ('category', models.CharField(choices=[('', 'select'), ('BEAUTY', 'Beauty'), ('PERSONAL_CARE', 'Personal Care'), ('MEDICINE_AND_TREATMENT', 'Medicine & Treatment'), ('NATURAL_AND_ORGANIC', 'Natural & Organic'), ('SUPPLEMENT_AND_VITAMINS', 'Supplements & Vitamins')], default='select', max_length=20)),
                ('width', models.IntegerField(default=232)),
                ('height', models.IntegerField(default=250)),
                ('label', models.CharField(choices=[('', 'select'), ('P', 'primary'), ('S', 'secondary'), ('D', 'danger')], default='select', max_length=15)),
                ('description', models.CharField(blank=True, max_length=150)),
                ('detail', models.TextField(blank=True, max_length=2500)),
                ('slug', models.SlugField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Item')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordered', models.BooleanField(default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField()),
                ('items', models.ManyToManyField(to='core.OrderItem')),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
