# Generated by Django 2.2.3 on 2019-07-18 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('category', models.CharField(choices=[('', 'select'), ('BTY', 'Beauty'), ('PER_CARE', 'Personal Care'), ('MED_TREAT', 'Medicine & Treatment'), ('N&O', 'Natural & Organic'), ('SUPP_AND_VIT', 'Supplements & Vitamins')], default='select', max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('width', models.IntegerField(default=232)),
                ('height', models.IntegerField(default=250)),
                ('slug', models.SlugField(blank=True, default='page-slug', unique=True)),
                ('description', models.CharField(max_length=160)),
                ('detail', models.TextField(max_length=2500)),
                ('is_favourite', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
