# Generated by Django 2.2.3 on 2019-07-18 05:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BookAppointment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('', 'select'), ('SIR', 'Sir'), ('MR', 'Mr'), ('MRS', 'Mrs'), ('MS', 'Ms'), ('NONE', 'None')], default='select', max_length=20)),
                ('full_name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(choices=[('', 'choose'), ('M', 'Male'), ('F', 'Female')], default='chose', max_length=10)),
                ('age', models.IntegerField()),
                ('symptoms', models.TextField(max_length=500)),
                ('date', models.DateField()),
                ('user', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
